FEATHERLESS_API_KEY="rc_f7f321c43fd326be8b15b795bed79c09593728b63d44be4ea136725352346390"
QUERY_PLANNING_AGENT_LLM_MODEL="Qwen/Qwen3-4B-Thinking-2507"
PLOT_TYPE_CHOOSER_AGENT_LLM_MODEL="mistralai/Mistral-Small-3.1-24B-Instruct-2503"
GOOGLE_API_KEY="AIzaSyAMAGBzl0g3VI6neKWEAy7ofaNArEr5V4k"
LLM_PROVIDER="featherless"
